#!/usr/bin/env bash
# installs nginx on web-01 server
apt-get update
apt-get -y install nginx
echo "Holberton School for the win!" > /usr/share/nginx/html/index.html
service nginx start
ufw allow 'Nginx HTTP'
