#!/usr/bin/env bash
#install load balancer
apt-get update
apt-get -y install haproxy
echo "frontend frontend_balancer
        bind *:80
        mode http
        default_backend backend_balancer
backend backend_balancer
        mode http
        balance roundrobin
        server 686-web-01 35.196.198.246:80 check
        server 686-web-02 34.73.64.187:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy start
