#!/usr/bin/env bash
# displays to infinity and beyond indefinitley
sudo bash -c "echo $BASHPID > /var/run/holbertonscript.pid"

trap "echo I hate the kill command; rm -f /var/run/holbertonscript.pid; exit" SIGTERM
trap "echo Y U no love me?; rm -f /var/run/holbertonscript.pid; exit" SIGINT
trap "rm -f /var/run/holbertonscript.pid; exit" SIGQUIT

while :
do
    echo "To infinity and beyond"
    sleep 2
done
