#!/usr/bin/env bash
# display content of ets/passwd file usng while loop and IFS

IFS=:
while read -r UN PW UI GI UII HD CS
do
	echo "The user $UN is part of the $GI gang, lives in $HD and rides $CS. $UI's place is protected by the passcode $PW, more info about the user here: $UII"
done < "/etc/passwd"
