#!/usr/bin/env bash
#displays the time for 12 hrs and 59 min
i=1
j=1

while [[ j -le 12 ]]; do
    echo "Hour:" $j
    while [[ i -le 59 ]]; do
	echo $i
	(( i++ ))
    done
        i=1
	(( j++ ))
done
