#!/usr/bin/env bash
# configure ubuntu server
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1[[:blank:]]*localhost/127.0.0.2 localhost/' ~/hosts.new
sed -i '2i8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
rm -f ~/hosts.new
